name: Build ubuntu20-gcc11-x64 Image

on:
  push:
    branches:
      - ci-images
  pull_request:
    branches:
      - ci-images
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: nmm0/distbvh-ubuntu20.04-gcc11-x64:ci-images
      CACHE_TAG: nmm0/distbvh-ubuntu20.04-gcc11-x64:buildcache
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' || github.ref == 'refs/heads/ci-images'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Cached Image
        run: docker pull ${{ env.IMAGE_TAG }}
        continue-on-error: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ubuntu20.04-gcc11-x64.dockerfile
          cache-from: type=registry,ref=docker.io/${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=docker.io/${{ env.CACHE_TAG }},mode=max
          push: ${{ (github.event_name == 'push' || github.ref == 'refs/heads/ci-images') && 'true' || 'false' }}
          tags: ${{ env.IMAGE_TAG }}
